version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - db
    command: npx prisma generate; npx prisma migrate dev; npx prisma db seed

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
