version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      mynet:
        ipv4_address: 192.168.48.10
    restart: always

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    networks:
      mynet:
        ipv4_address: 192.168.48.6
    command: echo "cham hoi cham hoi"
    depends_on:
      - db
    tty: true

volumes:
  db-data:

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.48.0/20"
