version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      # POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

    restart: always

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code

    depends_on:
      - db
    tty: true

volumes:
  db-data:
