version: "3.9"
services:
  db:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    # restart: always

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    entrypoint: ["/bin/sh", "./scripts/entrypoint.sh"]
    depends_on:
      - db

volumes:
  db-data: